### ISSUE TITLE
Errors and plugin not functioning not sure what I did wrong :/

### ISSUE THREAD

**Issue by adollaree** [rockquiet/JoinProtection#1]
[21:33:06] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'joinprotection' in plugin JoinProtection v1.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:875) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:314) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:298) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1961) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1923) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1152) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1131) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1124) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at net.minecraft.util.thread.IAsyncTaskHandler.bp(SourceFile:115) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1107) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1019) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3834-Spigot-3374045-52faa6b]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/kyori/adventure/text/minimessage/MiniMessage
        at me.rockquiet.joinprotection.MessageManager.sendMessage(MessageManager.java:22) ~[?:?]
        at me.rockquiet.joinprotection.commands.JoinProtectionCommand.onCommand(JoinProtectionCommand.java:37) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.minimessage.MiniMessage
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at me.rockquiet.joinprotection.MessageManager.sendMessage(MessageManager.java:22) ~[?:?]
        at me.rockquiet.joinprotection.commands.JoinProtectionCommand.onCommand(JoinProtectionCommand.java:37) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more

**Comment by rockquiet** [comment]
Hi, the plugin does not currently support **Spigot** servers. It only works on **Paper** (and forks of it such as Purpur) at the moment.

Please consider switching to Paper if there is no specific reason to continue using Spigot.

A great guide from the PaperMC team if you need some help: https://docs.papermc.io/paper/migration
